CREATE SCHEMA IF NOT EXISTS menu_database;
USE menu_database;

CREATE TABLE USER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Firebase_User_ID VARCHAR(255) NOT NULL
);

CREATE TABLE MENU (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Menu_Day DATE NOT NULL,
    User_ID INT NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES USER(ID)
);

CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    ImageURL VARCHAR(255),
    Weight BIGINT,
    WeightUnit VARCHAR(255),
    Calories BIGINT,
    Source VARCHAR(255) NOT NULL,
    Shared BOOLEAN NOT NULL
);

CREATE TABLE RECIPE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description BLOB,
    ImageURL VARCHAR(255),
    PreperationTime TIME,
    Servings DECIMAL(10, 2),
    Difficulty VARCHAR(255),
    Source VARCHAR(255) NOT NULL,
    Shared BOOLEAN NOT NULL
);

CREATE TABLE INGREDIENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Recipe_ID INT,
    Product_ID INT,
    Amount BIGINT,
    Amount_Unit VARCHAR(255),
    FOREIGN KEY (Recipe_ID) REFERENCES RECIPE(ID),
    FOREIGN KEY (Product_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE MENU_ITEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Menu_ID INT NOT NULL,
    MENU_ITEM_TYPE VARCHAR(255),
    Recipe_ID INT,
    Product_ID INT,
    FOREIGN KEY (Menu_ID) REFERENCES MENU(ID),
    FOREIGN KEY (Recipe_ID) REFERENCES RECIPE(ID),
    FOREIGN KEY (Product_ID) REFERENCES PRODUCT(ID)
);