name: MenuBackend Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./MenuBackend
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Building the project
      run: mvn clean compile
    - name: Running tests
      run: mvn test
    - name: Publish Test Summary Results
      if: always()
      run: npx github-actions-ctrf MenuBackend/target/surefire-reports/TEST-*.xml

