name: MenuBackend Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Building the project
      run: mvn clean compile -f ./MenuBackend/pom.xml
    - name: Running tests
      run: mvn test -f ./MenuBackend/pom.xml
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: always()
      with:
        files: |
          ./MenuBackend/src/test/resources/TestResults/result.json

